---
# Configuration of alternc-slavedns with playbook variables

- name: Create an alternc-slavedns configuration file (delfault.conf is ignored)
  fetch: 

- name: Protocol to access list of zones, http or https
  lineinfile:
    path: /etc/alternc/slavedns/defaults.conf
    regexp: ^PROTOCOL=
    line: PROTOCOL={{ alternc_slavedns_protocol }}
    state: present
    # backup: yes
    # alternc-slavedns dosn't handle well these backup files

- name: Master host where lies the list of zones
  lineinfile:
    path: /etc/alternc/slavedns/defaults.conf
    regexp: ^HOST=
    line: HOST={{ alternc_slavedns_master }}
    state: present

- name: Master host IP
  lineinfile:
    path: /etc/alternc/slavedns/defaults.conf
    regexp: ^MASTERIP=
    line: MASTERIP={{ alternc_slavedns_master_ip }}
    state: present


- name: Master host login
  lineinfile:
    path: /etc/alternc/slavedns/defaults.conf
    regexp: ^LOGIN=
    line: LOGIN={{ alternc_slavedns_login }}
    state: present

- name: Master host password
  lineinfile:
    path: /etc/alternc/slavedns/defaults.conf
    regexp: ^PASSWORD=
    line: PASSWORD={{ alternc_slavedns_+++password }}
    state: present

...
